#!/bin/bash

# Let script exit when a command fail
set -o errexit

# Add $HOME/.local/bin to path
export PATH=$PATH:$HOME/.local/bin

# Add Personal Package Archives
if command -v add-apt-repository > /dev/null 2>&1; then
    # python PPA
    sudo add-apt-repository --enable-source --yes ppa:deadsnakes/ppa

    # R PPA
    sudo apt-add-repository --enable-source --yes ppa:marutter/rrutter4.0
    sudo apt-add-repository --enable-source --yes ppa:c2d4u.team/c2d4u4.0+

    # Golang
    sudo apt-add-repository --enable-source --yes ppa:longsleep/golang-backports
else
    echo "add-apt-repository not available"
fi

# Running under WSL (Windows Subsystem for Linux)
if cat /proc/version | grep -q microsoft; then
    echo "Running in WSL mode..."

    # Windows User path
    USERPATH=/mnt/c/Users/$(powershell.exe '$env:UserName' | sed -e 's/\r//g')

    # Find .gitignore in Windows or import from config/
    if [ -e $USERPATH/.gitconfig ]; then
        echo "Using Windows .gitconfig file..."
        sudo ln -sf $USERPATH/.gitconfig ~/
    else
        echo "Using repo .gitconfig file..."
        sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/.gitconfig $HOME/
    fi

    # Find SSH key in Windows and import to WSL
    if [ ! -e $HOME/.ssh ]; then
        echo "Copying .ssh files to .ssh/..."
        cp -r $USERPATH/.ssh ~/
    fi

    sudo chmod 600 ~/.ssh/*

    if [ ! -h $HOME/.ssh/known_hosts ]; then
        echo "Creating symlink to known_hosts..."
        sudo ln -sf $USERPATH/.ssh/known_hosts ~/.ssh/known_hosts
    fi

    # Find gpg key and import from Windows
else
    echo "Running in normal mode..."

    # Import .gitignore from config/
    if [[ ! -e $HOME/.gitconfig ]]; then
        echo "Using repo .gitconfig file..."
        sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/.gitconfig $HOME/
    fi
fi

# tmux.conf
if command -v add-apt-repository > /dev/null 2>&1 && [ ! -e $HOME/.tmux.conf ]; then
    echo "Softlink from .tmux.conf to $HOME..."
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/.tmux.conf $HOME/.tmux.conf
fi

# gpg-agent.conf
if command -v gpg > /dev/null 2>&1 && [ ! -e $HOME/gpg-agent.conf ]; then
    echo "Softlink from gpg-agent.conf to $HOME..."
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/gpg-agent.conf $HOME/gpg-agent.conf
fi

# .vimrc
if command -v vim > /dev/null 2>&1 && [ ! -e $HOME/.vimrc ]; then
    echo "Softlink from .vimrc to $HOME..."
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/.vimrc $HOME/.vimrc
fi

# .wgetrc
if command -v wget > /dev/null 2>&1 && [ ! -e $HOME/.wgetrc ]; then
    echo "Softlink from .wgetrc to $HOME..."
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/config/.wgetrc $HOME/.wgetrc
fi

# oh-my-bash
if [ ! -d $HOME/.oh-my-bash ]; then
    bash -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"
fi

# .bashrc
if [ ! -h $HOME/.bashrc ]; then
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/.bashrc $HOME/.bashrc
fi

# Link .custom folder
if [ ! -h $HOME/.custom ]; then
    sudo ln -sf $(cd -P -- "$(dirname -- "$0")" && pwd -P)/.custom $HOME/.custom
fi

# Update packages
sudo apt update

# Update image
sudo apt --yes full-upgrade

exec bash; source $HOME/.bashrc
