#!/usr/bin/env bash

# Let script exit when a command fail
set -o errexit

# Let script exit if an unset variable is used
set -o nounset

# Update packages
sudo apt -y update
sudo apt -y full-upgrade

# Running under WSL (Windows Subsystem for Linux)
if cat /proc/version | grep Microsoft; then
  echo "Running in WSL mode..."
  WSL=true
else
  echo "Running in normal mode..."
  WSL=false
fi

# Get Windows username
if [[ $WSL ]]; then
  echo "Finding Windows username..."
  WINUSR=`cmd.exe /c echo %username%`
fi

# Install "Oh My Bash" & clean
sh -c "$(wget https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"

if [[ -d ~/.bashrc.pre-oh-my-bash ]]; then
  echo "Remove .pre-oh-my-bash..."
  rm -rf ~/.bashrc.pre-oh-my-bash
fi

# Define USERPATH running WSL mode
if [[ $WSL ]]; then
  echo "Windows 10 %USERPROFILE%..."
  USERPATH=/mnt/c/Users/$WINUSR
fi

# Use Windows .gitconfig if possible else use repo's version.
if [[ $WSL ]]; then
  if [[ -e $USERPATH/.gitconfig ]]; then
    echo "Using Windows' .gitconfig file..."
    ln -sf $USERPATH/.gitconfig ~/
  else
    echo "Using repo's .gitignore file..."
    ln -sf .gitconfig ~/
  fi
else
  echo "Using repo's .gitignore file..."
  ln -sf .gitconfig ~/
fi

if [[ $WSL ]]; then
  if [[ ! -d ~/.ssh ]]; then
    echo "Creating folder ~/.ssh/..."
    mkdir .ssh
  fi

  echo "Copying .ssh files to .ssh/..."
  cp $USERPATH/.ssh/id_rsa ~/.ssh/
  cp $USERPATH/.ssh/id_rsa.pub ~/.ssh/

  echo "Creating symlink to known_hosts..."
  ln -sf $USERPATH/.ssh/known_hosts ~/.ssh/known_hosts
fi

# Remove bloat
if [[ -e /etc/apt/apt.conf.d/20snapd.conf ]]; then
  echo "Removing /etc/apt/apt.conf.d/20snapd.conf..."
  sudo rm /etc/apt/apt.conf.d/20snapd.conf
fi

sudo apt autoremove snapd

# Clean
sudo apt -y autoremove
if [[ -d /var/lib/apt/lists ]]; then
  echo "Removing package list..."
  rm -rf /var/lib/apt/lists/*
fi
sudo apt clean -y