# GPG configuration for WSL and local development
use-agent
pinentry-program /usr/bin/pinentry-curses
default-key A2893BF0F2DF1B57
personal-digest-preferences SHA256
cert-digest-algo SHA256
default-preference-list SHA256 SHA384 SHA512 SHA224 AES256 AES192 AES CAST3 ZLIB BZIP2 ZIP Uncompressed
no-emit-version
no-comments
